### ISSUE TITLE
这个怎么用呀

### ISSUE THREAD

**Issue by mappjzc** [cloudwindy/gfwfucker#1]
python 2.7 好像不支持 async 
我换成python 3.5 好像又报
from asyncio import run 的错误

弱弱的问下，这个的运行环境应该怎么搭建呀？

另外请问大佬留个联系方式，微信QQ什么的吗？

**Comment by cloudwindy** [comment]
我们完全可以在issue里联系，不需要第三方联系方式
当前这个项目还没有完成，所以暂时无法正常运行，感谢关注

**Comment by mappjzc** [comment]
所以这个项目还会完成吗？我对这里面涉及的技术非常感兴趣，一直想写一个自己用的客户端和服务端。
依靠issue联系，感觉怪怪的……
毕竟是公开场合，需要注意言辞的说。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "cloudwindy"<notifications@github.com&gt;; 
发送时间: 2020年10月1日(星期四) 凌晨0:44
收件人: "cloudwindy/gfwfucker"<gfwfucker@noreply.github.com&gt;; 
抄送: "大脑开花"<jzc001@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [cloudwindy/gfwfucker] 这个怎么用呀 (#1)





 
我们完全可以在issue里联系，不需要第三方联系方式
 当前这个项目还没有完成，所以暂时无法正常运行，感谢关注

**Comment by cloudwindy** [comment]
是的 我正在完成这个项目
你可以在Telegram联系我：@SuperSkEy

**Comment by cloudwindy** [comment]
关于报错：请更新到最新版本Python 3.9/3.10
